<?php include('basePage.php'); ?>

<p align="left" class="textoNormal">Antes de leer las reglas,  debe aclararse que los t&eacute;rminos GO y Operador de juego, hacen  referencia a &eacute;stos &uacute;ltimos, siendo los encargados de regular el buen  funcionamiento de cada universo.<br>
</p>
<p align="left" class="textoNormal">&sect;1 Cuentas<br>
<br>
- Cada usuario puede tener una cuenta por Universo.<br>
- Cada cuenta s&oacute;lo puede ser utilizada por una persona. </p>
<div align="left" class="textoNormal"><br>
                                    <br>
                                    &sect;2 Multi-cuentas<br>
<br>
- Controlar m&aacute;s de una cuenta por universo est&aacute; estrictamente prohibido.<br>
- Si hay 2 o m&aacute;s jugadores en la misma IP (por ejemplo: parejas,  hermanos, etc&eacute;tera), o bien se juega desde lugares p&uacute;blicos  (cibercaf&eacute;s, universidades, escuelas,..) hay que intentar que nuestro  nick, email y contrase&ntilde;a, sean lo m&aacute;s originales posibles, a fin de  evitar coincidencias aleatorias con otros jugadores que pudieran  inducir a falsas multi-cuentas. El &uacute;nico privilegio permitido es estar  en la misma alianza, cualquier infracci&oacute;n a esto ser&aacute; considerada  pushing. En caso de suspensi&oacute;n mientras se juega desde un lugar  p&uacute;blico, se requerir&aacute; lo posible para poder constatar que realmente se  est&aacute; jugando desde un lugar p&uacute;blico y que, por tanto, forzosamente,  algunas coincidencias o interacciones en la misma IP son inevitables <strong>por desconocimiento</strong>.<br>
- Las cuentas que est&eacute;n jugando en la misma IP, en entornos privados  (hogares, trabajos...) no est&aacute;n autorizadas a interactuar de ning&uacute;n  modo (ni transportes, ni espionajes, ni ataques individuales o  conjuntos, etc).<br>
- Siempre es mejor informar de antemano a un GO de que dos personas  est&aacute;n jugando en el mismo Universo en la misma IP. &iexcl;Pero las reglas  seguir&aacute;n aplic&aacute;ndose!<br>
<br>
<br>
<br>
&sect;3 Cuidado de cuentas (account-sitting)<br>
<br>
El sitting s&oacute;lo puede darse bajo las siguientes condiciones.<br>
- Una cuenta s&oacute;lo puede ser cuidada durante un m&aacute;ximo de 12 horas seguidas.<br>
- Debes informar a un GO de tu Universo sobre el sitting.<br>
- Si el sitting est&aacute; permitido, se permite usar los recursos en un  planeta/luna para construir &lsquo;Edificios&rsquo;, y mejorar &lsquo;Investigaci&oacute;n&rsquo;  (tecnolog&iacute;as). NO se puede mover recursos entre planetas o lunas.<br>
- Antes de que una cuenta pueda ser cuidad de nuevo, el due&ntilde;o tiene que  entrar en su cuenta de nuevo. Dos personas no pueden cuidar la cuenta  de forma consecutiva.<br>
- Una vez que el propietario haya entrado, deben pasar 7 d&iacute;as para que la cuenta pueda ser cuidada por otro usuario<br>
- Una vez que el cuidador haya terminado, no podr&aacute; cuidar otra cuenta durante 7 d&iacute;as.<br>
<br>
<em><br>
NO SE PUEDE</em><br>
- No se permiten los movimientos de flotas mientras la cuenta se est&eacute;  cuidando, sin embargo, puedes salvar la flota si hay un ataque contra  la cuenta cuidada. El movimiento S&Oacute;LO puede ser un transporte o  despliegue a los planetas/lunas propios de la cuenta.<br>
- No est&aacute; permitido cuidar una cuenta en las 3 primeras semanas de un universo nuevo.<br>
- Cuando una cuenta se est&aacute; cuidando, s&oacute;lo se permite al cuidador  entrar en la cuenta. Si el due&ntilde;o de la cuenta entra, se considera que  el per&iacute;odo de cuidado ha terminado.<br>
- Usar m&uacute;ltiples cuidadores durante el per&iacute;odo de cuidado de una cuenta no est&aacute; permitido.<br>
<br>
<br>
</div>
<p align="left" class="textoNormal">&sect;4 Intercambio de cuentas<br>
<br>
Cualquier  cuenta entregada, est&aacute; relacionada con la persona que aparece en la  direcci&oacute;n de email permanente. Si los usuarios intercambian cuentas sin  la ayuda de un operador de juego, no se procesar&aacute;n quejas o peticiones  a menos que se originen desde las direcciones permanentes de las  cuentas respectivas.<br>
<br>
Los operadores de juego no s&oacute;lamente pueden cambiar dos cuentas con  facilidad, tambi&eacute;n lo hacen con mayor seguridad (al evitar robos de  cuentas), y tambi&eacute;n pueden hacer el intercambio sin necesidad de que se  intercambien las contrase&ntilde;as.<br>
<br>
Una cuenta s&oacute;lo podra ser intercambiada cada 15 d&iacute;as, a fin de evitar sittings encubiertos y account-sharing<br>
</p>
<p align="left" class="textoNormal"><br>
                                  &sect;5 Bashing<br>
<br>
-  Atacar una luna o planeta m&aacute;s de 6 veces con cualquier tipo de flota  (en un per&iacute;odo de 24 horas se considera bashing y no est&aacute; permitido). <br>
- Las misiones de Destruir lunas cuentan como ataques bajo el reglamento de bashing. <br>
- Los espionajes que terminen en batalla con empate, en el que se  obtengan beneficios en forma de escombros para el atacante, por la  destrucci&oacute;n de flota enemiga), o victoria para el atacante cuentan como  ataques bajo el reglamento de bashing.<br>
</p>
<p align="left" class="textoNormal"><br>
                      <em>Excepciones</em><br>
                      - El bashing s&oacute;lo est&aacute; permitido cuando tu Alianza est&eacute; en guerra con  otra alianza. (la Guerra debe ser anunciada en el Foro de OGame, en el  subforo adecuado.)<br>
                      - los ataques en los que la flota atacante sea destruida no cuentan en la regla de bashing.<br>
                      - Las flotas cuyo combate est&eacute; afectado por el bug del empate, est&aacute;n exentas de la regla de bashing.<br>
                      - Los ataques con misiles interplanetarios no cuentan en la regla de bashing.<br>
                      - No se computa el bashing al atacar a planetas de usuarios inactivos,  sin embargo, si el usuario vuelve de la inactividad y denuncia el  bashing, se sancionar&aacute; de igual modo.<br>
                      </p>
                      <p align="left" class="textoNormal"><br>
                                            &sect; Anexo V. Excepciones por declaraciones de guerra<br>
                                            -  La guerra no tendr&aacute; v&aacute;lidez hasta 24 horas despu&eacute;s de haberse hecho el  anuncio en el foro de OGame.  - Las declaraciones de guerra s&oacute;lo ser&aacute;n v&aacute;lidas si est&aacute;n formuladas  por el fundador de la alianza.  - Los jugadores no pueden declarar la guerra a t&iacute;tulo individual.  - No se permite una declaraci&oacute;n de guerra a m&uacute;ltiples alianzas, as&iacute;  como declaraciones de guerra a todo el universo. Cada declaraci&oacute;n de  guerra debe ata&ntilde;er s&oacute;lo a la alianza y canteras, si las tuviera.<br>
                                            </p>
                                            <p align="left" class="textoNormal"><br>
                                                                  </p>
                                                                  <p align="left" class="textoNormal">&sect;6 Pushing<br>
                                                                                        <br>
                                                                                        -  Se considera pushing cuando un jugador de menor puntuaci&oacute;n env&iacute;a  recursos a un jugador de mayor puntuaci&oacute;n, al ganar ventaja sobre los  dem&aacute;s de forma injusta. Esto tambi&eacute;n incluye el env&iacute;ar recursos a un  jugador de mayor puntuaci&oacute;n que te extorsione.<br>
                                                                                        - El pushing no est&aacute; permitido bajo ninguna circunstancia.<br>
                                                                                        - Si recibes recursos inesperadamente de un jugador de menor  puntuaci&oacute;n, no te los puedes quedar. Debes devolverlos inmediatamente e  informar a un GO en caso de reincidencia, para suspender al jugador.<br>
                                                                                        - Los pr&eacute;stamos no est&aacute;n permitidos.<br>
                                                                                        - Los comercios deben ser completados en un m&aacute;ximo de 48 horas.<br>
                                                                                        - "comerciar" con ratios desmesurados a favor del jugador con m&aacute;s  puntos, A relaci&oacute;n metal:cristal:deuterio, 1:1:1 se considera ilegal.  Si bien se recomienda que la relaci&oacute;n apropiada para comerciar sea  3:2:1, cualquier jugador podr&aacute; comerciar con su propia relaci&oacute;n que  considere apropiada, entre los m&aacute;rgenes 3,5:2.5:1, y 2:1,5:1. Los  comercios en ratios superiores o inferiores a los establecidos, est&aacute;n  estrictamente prohibidos.<br>
                                                                                        - Los miembros de una alianza podr&aacute;n ayudar a recuperar a un aliado la  flota perdida, previa autorizaci&oacute;n de un GO que indicar&aacute; la cantidad de  recursos que el jugador puede recibir.<br>
                                                                                        <br>
                                                                                        <em>Ejemplos</em> (Las infracciones NO est&aacute;n limitadas a &eacute;stas)</p>
                                                                                        <p align="left" class="textoNormal"> - Un jugador de menor puntuaci&oacute;n env&iacute;a recursos a un jugador de mayor puntuaci&oacute;n.<br>
                                                                                                              - Un jugador de menor puntuaci&oacute;n env&iacute;a su flota en un ataque contra un  jugador de mayor puntuaci&oacute;n, de modo que el jugador pueda recolectar  los escombros creados.<br>
                                                                                                              - Transportar recursos a un planeta que despu&eacute;s es atacado para recogerlos.<br>
                                                                                                              <br>
                                                                                                              <em>Reciclajes conjuntos</em><br>
                                                                                                              - env&iacute;ar recuros a un jugador de puntuaci&oacute;n m&aacute;s alta despu&eacute;s de haberle  ayudado a reciclar escombros, S&Oacute;LO est&aacute; permitido cuando &eacute;l/ella  obtenga permiso de un GO de su universo.<br>
                                                                                                              <br>
                                                                                                              <em>Botines/Cazarrecompensas</em><br>
                                                                                                              - Los botines y cazarrecompensas deben ser declarados en el foro para  ser puestos en conocimiento. Todo lo que no se haya declarado en el  foro, en la secci&oacute;n correspondiente, ser&aacute; tratado como pushing si  procediera.<br>
                                                                                                              - Los botines s&oacute;lo se pueden pagar despu&eacute;s de que el objetivo haya sido  destruido, nunca por adelantado, &eacute;stos deben ce&ntilde;irse estrictamente al  juego.</p>
                                                                                                              <div align="left" class="textoNormal"><br>
                                                                                                                                      <br>
                                                                                                                                      </div>
                                                                                                                                      <p align="left"> <span class="textoNormal">&sect;7 Intentos de creaci&oacute;n de lunas<br>
                                                                                                                                                                   <br>
                                                                                                                                                                   - Los intentos de creaci&oacute;n de lunas est&aacute;n permitidos.<br>
                                                                                                                                                                   - Se necesita el permiso de un GO antes de poder llevarlos a cabo.<br>
                                                                                                                                                                   - Debe tomarse la precauci&oacute;n de que el jugador de mayor puntuaci&oacute;n no  obtenga beneficios de un intento de luna. Esto es pushing y es  sancionable.<br>
                                                                                                                                                                   - La flota destinada al intento de creaci&oacute;n de luna nunca debe superar  el 20% de probabilidad de creaci&oacute;n de luna (nunca podr&aacute; ser superior a  2.002.000 escombros en total)<br>
                                                                                                                                                                   <br>
                                                                                                                                                                   &sect;8 Uso de bugs (errores del juego), scripts, programas externos, bots...<br>
                                                                                                                                                                   <br>
                                                                                                                                                                   - El uso de bugs no est&aacute; permitido bajo ninguna circunstancia.<br>
                                                                                                                                                                   - Si un jugador encuentra un bug, tiene que informar al equipo de  administraci&oacute;n lo antes posible (p.ej:
                                                                                                                                                                           a trav&eacute;s del foro, IRC o E-mail).<br>
                                                                                                                                                                   - Aprovecharse de un bug y no reportarlo, ser&aacute; sancionado.<br>
                                                                                                                                                                   - Cualquier m&eacute;todo o intento que detenga o ralentice injustamente la  capacidad de un usuario para jugar a OGame, est&aacute; estrictamente  prohibido.<br>
                                                                                                                                                                   -Usar un bot, script o cualquier otro programa o m&eacute;todo, que realice  acciones de forma automatizada en OGame, est&aacute; totalmente prohibida,  adem&aacute;s, la empresa podr&iacute;a tomar medidas legales contra el autor en caso  de que los da&ntilde;os provocados sean de importancia o pongan en peligro la  estabilidad de cualquiera de sus Universos.</span></p>
                                                                                                                                                                   <p align="left" class="textoNormal"><br>
                                                                                                                                                                                         &sect;9 Idioma<br>
                                                                                                                                                                                         <br>
                                                                                                                                                                                         - El idioma oficial en <a target="_blank" onclick="Mostrar(\'http://ogame.com.es/portal/www.ogame.com.es\')">OGame.es</a> y su <a target="_blank" onclick="Mostrar(\'http://board.ogame.com.es\')">foro</a> es el Espa&ntilde;ol, o denominado com&uacute;nmente, castellano.<br>
                                                                                                                                                                                                                          - Los mensajes y p&aacute;ginas de Alianza que no est&eacute;n en espa&ntilde;ol, no est&aacute;n permitidas.<br>
                                                                                                                                                                                                                          - Las impersonalizaciones, o intentar hacerse pasar por miembros de la  administraci&oacute;n no est&aacute; permitido bajo ninguna circunstancia.<br>
                                                                                                                                                                                                                          - Los insultos no est&aacute;n permitidos<br>
                                                                                                                                                                                                                          <br>
                                                                                                                                                                                                                          <strong>Anexo. Excepciones al Idioma</strong></p>
                                                                                                                                                                                                                          <p align="left"> <span class="textoNormal">-  Se permite el uso de cualquier idioma en mensajes privados entre  usuarios, circulares de una alianza, y mensajes privados en el foro.<br>
                                                                                                                                                                                                                                                       - Se permite que una p&aacute;gina de Alianza est&eacute; en un idioma diferente,  siempre que aparezca la respectiva traducci&oacute;n a Espa&ntilde;ol junto a ella.<br>
                                                                                                                                                                                                                                                       - Si un mensaje reportado en el juego, est&aacute; en un idioma que no sea  espa&ntilde;ol, ser&aacute; sancionado, sea cual fuere el motivo del reporte.<br>
                                                                                                                                                                                                                                                       </span></p>
                                                                                                                                                                                                                                                       <p align="left" class="textoNormal">&sect;10 Uso incorrecto del boton "Reportar mensaje a GO"<br>
                                                                                                                                                                                                                                                                             </p>
                                                                                                                                                                                                                                                                             <p align="left" class="textoNormal"> Usar la funci&oacute;n de reportar mensaje, para informar de un mensaje que no  contenga insultos, es una violaci&oacute;n de las reglas y ser&aacute; sancionado.</p>
                                                                                                                                                                                                                                                                                                   <p align="left" class="textoNormal"><br>
                                                                                                                                                                                                                                                                                                                         &sect;11 Amenazas en la vida real<br>
                                                                                                                                                                                                                                                                                                                         </p>
                                                                                                                                                                                                                                                                                                                         <p align="left" class="textoNormal"> Insinuar que vas a localizar a una persona, para da&ntilde;arla, est&aacute;  estrictamente prohibido, tanto en el foro como en el juego. Todas las  amenazas en la vida real, que puedan ser contrastadas mediante el  juego, ser&aacute;n sancionadas.<br>
                                                                                                                                                                                                                                                                                                                                               </p>
                                                                                                                                                                                                                                                                                                                                               <div align="left" class="textoNormal"><br>
                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                       <p align="left"> <span class="textoNormal">&sect;12 Spam, insultos y contenido ofensivo<br>
                                                                                                                                                                                                                                                                                                                                                                                                    </span></p>
                                                                                                                                                                                                                                                                                                                                                                                                    <p align="left" class="textoNormal"> - El spam, los insultos, y contenido ofensivo no est&aacute;n permitidos.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                          <p align="left" class="textoNormal"><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <p align="left"> <span class="textoNormal">&sect;13 Racismo, xenofobia, apolog&iacute;a, pol&iacute;tica<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </span></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <p align="left" class="textoNormal">-  Cualquier tipo de expresi&oacute;n racista o xen&oacute;foba, ya sea por medio de  im&aacute;genes, alianzas, o nicks, ser&aacute; sancionada de manera permanente e  irrevocable. <br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   - Cualquier tipo de expresi&oacute;n r&aacute;dical pol&iacute;tica (nazismo, fascismo,  etc), ya sea por medio de im&aacute;genes, nombres de alianza o nicks, ser&aacute;  sancionada de manera permanente e irrevocable.<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   - La apolog&iacute;a al terrorismo, o cualquier otra ideolog&iacute;a extrema, en  cualquiera de las formas mencionadas previamente, ser&aacute; sancionada.<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   - No se permiten nombres de alianzas que hagan referencia a formaciones  extremistas, radicales, nacionalistas, terroristas, racistas o  xen&oacute;fobas, tampoco las que hagan alusiones a partidos pol&iacute;ticos o  t&eacute;rminos con connotaciones pol&iacute;ticas. Los miembros de este tipo de  alianzas, ser&aacute;n baneados sin posibilidad de anulaci&oacute;n de la suspensi&oacute;n.<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   - OGame no es un lugar para hacer propaganda pol&iacute;tica, por lo que  cualquier tipo de expresi&oacute;n nacionalista tanto en el foro como en el  juego, ser&aacute; sancionada. Se entiende por nacionalismo, el que proclama  la independencia de regiones que actualmente no se consideran una  naci&oacute;n, ya sea en el estado espa&ntilde;ol, argentino, o cualquier otro...<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   - No se permiten las alianzas cuyo contenido sea pol&iacute;tico, sea del tipo  que fuere. OGame no es un lugar para discursos pol&iacute;ticos. Existen otros  foros y p&aacute;ginas web dedicadas especialmente a la pol&iacute;tica</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div align="left" class="textoNormal"><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <p align="left"> <span class="textoNormal">&sect;14 Pornograf&iacute;a, denigraci&oacute;n a la mujer, hombres, ni&ntilde;os, ancianos..., sexismo</span></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p align="left"> <span class="textoNormal"><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     -  Colocar im&aacute;genes pornogr&aacute;ficas en una alianza ser&aacute; motivo de sanci&oacute;n  del fundador, dependiendo de la gravedad, el resto de miembros podr&iacute;an  ser baneados igualmente.<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     - Las alianzas con nombres que hagan alusi&oacute;n a entornos sexuales,  lugares de encuentros sexuales o pr&aacute;cticas sexuales, est&aacute;n  estrictamente prohibidas.<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     - Cualquier imagen que denigre a mujeres, ancianos, ni&ntilde;os, o personas  con malformaciones, tanto en el juego como en el foro, ser&aacute; sancionada.<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     - Cualquier expresi&oacute;n, ya sea por medio de im&aacute;genes, nicks, nombres de  alianza, etc, cuyo objetivo sea fomentar el sexismo, ser&aacute; sancionado.</span></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <p align="left" class="textoNormal"><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <p align="left"> <span class="textoNormal">&sect;15 Respeto</span></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p align="left"> <span class="textoNormal"><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     -Acusar indiscriminadamente a un jugador sin aportar pruebas, ser&aacute; sancionado</span></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div align="left" class="textoNormal"><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <p align="left"> <span class="textoNormal">&sect;16 Contactar con operadores de juego</span></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p align="left" class="textoNormal"><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -  En caso de ser sancionado, se tiene derecho a solicitar la revisi&oacute;n del  ban por parte de un Superoperador del juego, siempre que sea evidente  una posible malinterpretaci&oacute;n de las reglas. En cualquier caso,  intentar contactar con personas superiores en el equipo de OGame u  otros operadores de juego, para conseguir la anulaci&oacute;n de una sanci&oacute;n  que fue impuesta correctamente, ser&aacute; sancionada en caso de haberse  conseguido el objetivo.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div align="left" class="textoNormal"><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p align="left"> <span class="textoNormal">&sect;17 Violaciones de las reglas<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     - una violaci&oacute;n de las reglas puede resultar en una sanci&oacute;n de al menos  1 d&iacute;a, y podr&iacute;a llegar a ser una sanci&oacute;n permanente. Esta sanci&oacute;n puede  ser tanto con modo de vacaciones, como sin &eacute;l.<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     - Puedes ver todas las suspensiones de tu universo en las <a target="_blank" onclick="Mostrar(\'http://board.ogame.com.es/thread.php?threadid=23715\')">Listas de baneados</a>. <br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             - si est&aacute;s baneado, ponte en contacto con los GO de tu universo por medio de la direcci&oacute;n de email <a target="_blank" onclick="Mostrar(\'http://www.ogame.com.es/portal/?go=team&amp;lang=es\')">respectiva</a>.  Pulsando en el nombre del operador de juego en la lista de baneados te  permitir&aacute; ponerte en contacto con ellos de forma autom&aacute;tica si tu  cliente de correo est&aacute; configurado correctamente.</span></p>